# Reggie ERP
Put property computer location of real data and access shadowbook csv files.

In [1]:
access=r'/kaggle/input/accounts/access.csv' 
data=r'/kaggle/input/accounts/data.csv'

#### Change nothing below:

In [2]:

from datetime import datetime
import time
start=time.time()
print("Running Reggie Report on: ", datetime.today().strftime('%Y-%m-%d'))

Running Reggie Report on:  2022-08-08

# Access

In [3]:
import pandas as pd

aDF=pd.read_csv(access)
aDF.head()

,VOUCHER#,VOUCHER DATE,PROCESS DATE,INVOICE#,INVOICE DATE,VENDOR,AMOUNT,DESCRIPTION,VOU#,REQ#,ACCOUNT ID,FY
0,V12345,8/8/2022,8/8/2022,JE123456,8/8/2022,WALMART,387.52,Food,PR,Y,20504-05-987000402-123456,FY23
1,V12346,8/9/2022,8/8/2022,JE123457,8/9/2022,TESLA,962.14,Car,PR,Y,20504-05-987000402-987654,FY23
2,V12347,8/10/2022,8/8/2022,JE123458,8/10/2022,AMAZON,17.20,Stuff,PR,Y,20504-05-987000402-123456,FY23
3,V12348,8/11/2022,8/8/2022,JE123459,8/11/2022,AMAZON,26.38,Computer,PR,Y,20504-05-987000402-888999,FY23
4,V12349,8/12/2022,8/8/2022,JE123460,8/12/2022,TACO,45.00,NaN,PR,Y,98204-05-987000402-777666,FY23

# Data

In [4]:
df=pd.read_csv(data)
df.head()

,GL Account,GL Description,Date,Source,Reference Number,Description,Opening Balance,YTD Debits,YTD Credits
0,20504-05-987000402-123456,ReggieCR,8/8/2022,JE,AAVCDF6100,PR,NaN,387.52,NaN
1,20504-05-987000402-987654,ReggieCR,8/8/2022,JE,AAVCDF6101,PR,NaN,962.14,NaN
2,20504-05-987000402-123456,ReggieCR,8/8/2022,JE,AAVCDF6102,PR,NaN,17.20,NaN
3,20504-05-987000402-888999,ReggieCR,8/8/2022,JE,AAVCDF6103,PR,NaN,26.38,NaN
4,98204-05-987000402-777666,ReggieCR,8/8/2022,JE,AAVCDF6104,PR,NaN,45.00,NaN

In [5]:
df[' YTD Credits']=df[' YTD Credits'].fillna(0)
df.head()

,GL Account,GL Description,Date,Source,Reference Number,Description,Opening Balance,YTD Debits,YTD Credits
0,20504-05-987000402-123456,ReggieCR,8/8/2022,JE,AAVCDF6100,PR,NaN,387.52,0.0
1,20504-05-987000402-987654,ReggieCR,8/8/2022,JE,AAVCDF6101,PR,NaN,962.14,0.0
2,20504-05-987000402-123456,ReggieCR,8/8/2022,JE,AAVCDF6102,PR,NaN,17.20,0.0
3,20504-05-987000402-888999,ReggieCR,8/8/2022,JE,AAVCDF6103,PR,NaN,26.38,0.0
4,98204-05-987000402-777666,ReggieCR,8/8/2022,JE,AAVCDF6104,PR,NaN,45.00,0.0

In [6]:
df = df.assign(DataTotal = df[' YTD Debits'] - df[' YTD Credits'])
df.head()

,GL Account,GL Description,Date,Source,Reference Number,Description,Opening Balance,YTD Debits,YTD Credits,DataTotal
0,20504-05-987000402-123456,ReggieCR,8/8/2022,JE,AAVCDF6100,PR,NaN,387.52,0.0,387.52
1,20504-05-987000402-987654,ReggieCR,8/8/2022,JE,AAVCDF6101,PR,NaN,962.14,0.0,962.14
2,20504-05-987000402-123456,ReggieCR,8/8/2022,JE,AAVCDF6102,PR,NaN,17.20,0.0,17.20
3,20504-05-987000402-888999,ReggieCR,8/8/2022,JE,AAVCDF6103,PR,NaN,26.38,0.0,26.38
4,98204-05-987000402-777666,ReggieCR,8/8/2022,JE,AAVCDF6104,PR,NaN,45.00,0.0,45.00

In [7]:
df=df[['GL Account', 'DataTotal']]
df.head()

                  GL Account  DataTotal
0  20504-05-987000402-123456     387.52
1  20504-05-987000402-987654     962.14
2  20504-05-987000402-123456      17.20
3  20504-05-987000402-888999      26.38
4  98204-05-987000402-777666      45.00

In [8]:
df['GL Account'] = df['GL Account'].astype(str).apply(lambda x: x.replace('-', ''))
df.head()

               GL Account  DataTotal
0  2050405987000402123456     387.52
1  2050405987000402987654     962.14
2  2050405987000402123456      17.20
3  2050405987000402888999      26.38
4  9820405987000402777666      45.00

In [9]:
df = df.groupby('GL Account')['DataTotal'].sum().reset_index()
df.head()

               GL Account  DataTotal
0  1234567987654000111333      52.35
1  1234567987654000555555      56.42
2  2050405987000402123456    2946.18
3  2050405987000402888999      26.38
4  2050405987000402987654     962.14

In [10]:
for d in df['GL Account']:
    print(d)

1234567987654000111333
1234567987654000555555
2050405987000402123456
2050405987000402888999
2050405987000402987654
9820405987000402444333
9820405987000402777666
9820405987000402990099

In [11]:
print("Done. Finished in ", round((time.time()-start), 4), " seconds")

Done. Finished in  0.3089  seconds