# Accounting Automated
The original rough draft verision can be found on my GitHub here: https://github.com/ScottFrederickSchmidt/AccountingAutomation/blob/main/AccountingAutomation

-------

## Introduction
My simple explained accounting automation program will save a small business <b> over 7% of total accounting costs </b>, according to a senior data science python architect at a fortune 100 company. The project already has the support in some form of three computer science directors at Illinois State University and three senior level programmers at a fortune 100 company. Here is a follow up and finalized verision to clearly explain each individual step on how the accounting automation program works. 

A third of an accountant's day is spent reconciling incorrect, missing or newly posted transactions. This Python pandas dataFrame data science automation program that compares thousands of data transactions to database records which detects unbalanced accounts, new transactions,and human error. This will decrease accounting costs by over 7% yearly according to a Python senior data science architect at a fortune100. This Python accounting automation program will compare thousands of real data transactions and database accounting records, detect new transactions and can increase the efficiency of an accounting team by uo to 30%.

----------
## Competitive Advantage
<i><b>"How will this automation program show a competitive advantage versus SAP ERP?" </b>
    -C.S. director of a major university, PHD in C.S., Former SQL Architect. 

This is the best question for the the project. Mid and small businesses benefit from Python automation scripts at little to no cost. In fact, it has been proven that: <i>"Midsized companies (fewer than 1,000 employees) are more likely to spend around 10 million to 20 million at most, and small companies are not likely to have the need for a fully integrated SAP ERP system unless they have the likelihood of becoming midsized" </i> (Monk, 2009). Yes, 99% of fortune 100 companies use SAP ERP which can handle big data and should be used for any large company. However, Python using pandas can easily handle csv files if less than a million rows with no RAM issues. Therefore, all small businesses should consider using simply programming scripts to help accounting processes. 

In conclusion, yes, if there is a better program with lower costs that program should instead be implemented. But most small companies cannot afford a fancy system that will costs million(s) of dollars.

Sources:
Monk, Ellen F.; Wagner, Brej J. (2009). Concepts in enterprise resource planning (3rd ed.). Boston: Thomson Course Technology. pp. 23–34. ISBN 978-1-4239-0179-2.

---------------------
    
## Save Two Files in CSV format
  <b> Simple! This is the ONLY thing we need do to do.</b>  Python will do the rest! Python can read these excel sheets on the backend. They must be saved in the correct Property/Location spot. To find the location of an Excel file on your computer do the following:
1. Right click on Excel sheet
2. Copy paste the Location
3. End with the excel file title name.
    
In the end, it should look like the below: <br>
    `access=r'C:\Users\scott\OneDrive\Desktop\access.csv'`
    
 <br> Due to CSV files saving long numbers in scientific notation, it is easest to save the file as a .xlsx file.

In [1]:
access=r'C:\Users\sschm\Desktop\automate\access.xlsx'
data=r'C:\Users\sschm\Desktop\automate\data.xlsx'

#NOTHING TO BE CHANGED BELOW THIS!
import csv, time
import pandas as pd
from datetime import date

#DISPLAY REPORT ON TODAY'S DATE:
print("Running Data to Access report on: ", date.today().strftime("%m-%d-%Y") )
start=time.time()

Running Data to Access report on:  03-03-2022

## View Original Data
Using .head() can show the columns and first five rows of a csv file.

In [2]:
dataDF=pd.read_excel(data)
dataDF.head()

,GL Account,Date,Post Date,Record Date,JE,Invoice,YTD Debits,YTD Credits
0,1234411-999999999-120000,2022-01-02,2022-01-02,2022-01-08,39495923,123456,34.21,NaN
1,1234411-999999999-120000,2022-01-03,2022-01-03,2022-01-09,39495924,123457,234.54,NaN
2,1234411-999999999-120000,2022-01-04,2022-01-04,2022-01-10,39495925,123458,23.34,NaN
3,1234411-999999999-120000,2022-01-05,2022-01-05,2022-01-11,39495926,123459,87.43,NaN
4,1234411-999999999-120000,2022-01-06,2022-01-06,2022-01-12,39495927,123460,987.20,NaN

## View Original Access Data
Using .head() can show the columns and first five rows of a csv file.

In [3]:
accessDF=pd.read_excel(access) 
accessDF.head()

,ACCOUNT ID,Date,Post Date,Record Date,JE,Invoice,INVOICE AMOUNT,REQ#
0,12344-11-999999999-120000,2022-01-02,2022-01-02,2022-01-08,39495923,123456,34.21,D July
1,12344-11-999999999-120000,2022-01-03,2022-01-03,2022-01-09,39495924,123457,234.54,D July
2,12344-11-999999999-120000,2022-01-04,2022-01-04,2022-01-10,39495925,123458,23.34,D July
3,12344-11-999999999-120000,2022-01-05,2022-01-05,2022-01-11,39495926,123459,87.43,July
4,12344-11-999999999-120000,2022-01-06,2022-01-06,2022-01-12,39495927,123460,987.20,D Aug

# Group Transaction Data by Accounting Subtotals
The pandas library will read the excel csv files. The things that happen are as follows:
1. Create an ending Amount column by subtracting debits and credits.
2. Filter the GL Account and Ending Amount. These are the only two columns we need.
3. Use a dataframe groupby for each accounting object code to get all the accounting subtotals.
4. Temporarily delete hypens because Access does not have any hypens.

#### a. Create an ending Amount column by subtracting debits and credits. 
Most YTD Credits will be NA which is equilavent to 0.

In [4]:
dataDF['YTD Credits'].fillna(0, inplace=True)
dataDF['Ending Amount'] = dataDF.apply(lambda x: x['YTD Debits'] - x['YTD Credits'], axis = 1)
dataDF.head()

,GL Account,Date,Post Date,Record Date,JE,Invoice,YTD Debits,YTD Credits,Ending Amount
0,1234411-999999999-120000,2022-01-02,2022-01-02,2022-01-08,39495923,123456,34.21,0.0,34.21
1,1234411-999999999-120000,2022-01-03,2022-01-03,2022-01-09,39495924,123457,234.54,0.0,234.54
2,1234411-999999999-120000,2022-01-04,2022-01-04,2022-01-10,39495925,123458,23.34,0.0,23.34
3,1234411-999999999-120000,2022-01-05,2022-01-05,2022-01-11,39495926,123459,87.43,0.0,87.43
4,1234411-999999999-120000,2022-01-06,2022-01-06,2022-01-12,39495927,123460,987.20,0.0,987.20

#### b. Filter the GL Account and Ending Amount. These are the two columns Python needs.

In [5]:
dataDF=dataDF.filter(['GL Account', 'Ending Amount'])
dataDF.head()

                 GL Account  Ending Amount
0  1234411-999999999-120000          34.21
1  1234411-999999999-120000         234.54
2  1234411-999999999-120000          23.34
3  1234411-999999999-120000          87.43
4  1234411-999999999-120000         987.20

#### c. Use a dataframe groupby for each accounting object code to get all the accounting subtotals.

In [6]:
#dataList=dataDF.to_dict(orient='list')
dataTotals=dataDF.groupby('GL Account')['Ending Amount'].sum().reset_index()
dataTotals.head()

                 GL Account  Ending Amount
0  1234411-999999999-120000        2021.48
1  1234411-999999999-550000         931.78
2  1234411-999999999-900000         410.97
3  1234567-765432111-123456         100.00
4  5555555-555555555-555555          64.55

#### d. Temporarily delete hypens because Access does not have any hypens. Python and Excel will not recognize account numbers as a match unless they are exactly the same.

In [7]:
dataTotals['GL Account'] = dataTotals['GL Account'].str.replace('-', '') 
dataTotals.head()

               GL Account  Ending Amount
0  1234411999999999120000        2021.48
1  1234411999999999550000         931.78
2  1234411999999999900000         410.97
3  1234567765432111123456         100.00
4  5555555555555555555555          64.55

# Group Access Data by Accounting Subtotals
This is a sample shadowbook. nornally in the form of SQL or Access. Here is a sample of what most Access shadow book data could look like. The same procedures will be used as the data subtotals. Now look at the accounting subtotals on data and access. We can clearly see that the first three subtotals balance correctly. The last account nunmber does not balance.

In [8]:
accessDF=accessDF.filter(['ACCOUNT ID', 'INVOICE AMOUNT', 'REQ#']) #Only need these 3 columns
accessTotals = accessDF.groupby('ACCOUNT ID')['INVOICE AMOUNT'].sum().reset_index() #Sum totals by account number
accessTotals['ACCOUNT ID'] = accessTotals['ACCOUNT ID'].str.replace('-', '') #gets rid of hyphens 
accessTotals.head()

               ACCOUNT ID  INVOICE AMOUNT
0  1234411999999999120000         2021.48
1  1234411999999999550000          931.78
2  1234411999999999900000          410.97
3  5555555555555555555555           64.64

# Compare Access and Real Data 
Do the real transaction accounting object codes and shadowbook accounting subtoals match? Python will soon find out! Note: To all the expert computer scientists out there, I do realize I could of use a join statement. However, in the original draft I did it the probably more complex way using two for loops. A join statement would likely make the code more readable.

In [9]:
for d in dataTotals['GL Account']: #checks each data account 
    for a in accessTotals['ACCOUNT ID']: # checks each account in Access...
        if d==a: #if Data and Access Account are the same then do the following:
            dRow=dataTotals.loc[dataTotals['GL Account']==d]
            aRow=accessTotals.loc[accessTotals['ACCOUNT ID']==a]
            dSUM=round(float(dRow['Ending Amount'].values), 2) #data Subtotal Number
            aSUM=round(float(aRow['INVOICE AMOUNT'].values),2) #access Subtotal Number
            if  dSUM==aSUM: 
                continue; #nothing else needs to be done.
                #hyphen=a[0:5]+"-"+a[5:7]+"-"+a[7:16]+"-"+a[16:] #adds hyphens to account number, easier to copy/paste
                #print(d, dSUM, "data matches access: ", aSUM, hyphen)
            else:
                hyphens=a[0:5]+"-"+a[5:7]+"-"+a[7:16]+"-"+a[16:] #adds hyphens to account number, easier to copy/paste
                print(a, " Access-----check account----- Data", hyphens)
                #print(dSUM, " data DOES NOT match access ", aSUM, ". Difference is: ", round(float(dSUM-aSUM), 2) 
print("Finished matching data to access accounts in: ", round(time.time()-start, 3), " seconds");
print("----------END SECTION1 ----------")

5555555555555555555555  Access-----check account----- Data 55555-55-555555555-555555
Finished matching data to access accounts in:  2.727  seconds
----------END SECTION1 ----------

#### Python correctly noticed that the account number 55555-55-555555555-555555 does not balance.

# Check for Missing D in Req Column
Has something posted? When something has posted as a real data transaction, Access 'Req' column must be updated with a D. Normally, this takes a great deal of time by having to check EVERY individual account. When a new transaction with real data is recorded, a D is required in REQ# column in Access. Case must equal true, otherwise dec will be accidently pulled onto the dataFrame when it should not be.

In [10]:
accessDF=accessDF.dropna(subset=['REQ#'])
accessDF=accessDF.loc[accessDF['REQ#'].str.contains("D", case=True)] #keeps only access rows with a "D"
print(accessDF)

                   ACCOUNT ID  INVOICE AMOUNT    REQ#
0   12344-11-999999999-120000           34.21  D July
1   12344-11-999999999-120000          234.54  D July
2   12344-11-999999999-120000           23.34  D July
4   12344-11-999999999-120000          987.20   D Aug
5   12344-11-999999999-120000          654.76   D Aug
6   12344-11-999999999-550000           12.10   D Jan
7   12344-11-999999999-550000           54.34   D Jan
9   12344-11-999999999-900000           34.20   D May
10  12344-11-999999999-900000          342.34   D May
12  55555-55-555555555-555555           32.32   D Jan

In [11]:
accessDsum=accessDF.groupby('ACCOUNT ID')['INVOICE AMOUNT'].sum().reset_index()
accessDsum['ACCOUNT ID'] = accessDsum['ACCOUNT ID'].str.replace('-', '') #gets rid of hyphens 
accessDsum.head()

               ACCOUNT ID  INVOICE AMOUNT
0  1234411999999999120000         1934.05
1  1234411999999999550000           66.44
2  1234411999999999900000          376.54
3  5555555555555555555555           32.32

#### Compare Data to Access Posted Accounts

In [12]:
#GET EVERY REAL DATA ACCOUNTING NUMBER USED:
dataAccounts=dataDF['GL Account'].unique() #finds only unique accounts
dataAcc=[] #final list

for acc in dataAccounts:
    dataAcc.append(acc.replace('-', '') ) #removes hypens

#CHECK DATA FOR UNBANACED ACCOUNTS:
for account in accessDsum['ACCOUNT ID']: # checks each account in Access...
    aRow=accessDsum.loc[accessDsum['ACCOUNT ID']==account]
    dRow=dataTotals.loc[dataTotals['GL Account']==d]
    accessDtotal=round(float(aRow['INVOICE AMOUNT'].values),2) #access Subtotal Number
    dataTotal=round(float(dRow['Ending Amount'].values), 2) #datat Subtotal Number
    if account in dataAcc: #only need to check for Data Accounts 
        hyphens=account[0:5]+"-"+account[5:7]+"-"+account[7:16]+"-"+account[16:] #see note at end
        if accessDtotal==dataTotal:
            continue; #nothing else is needed to be done.
            #print(account, " is likely correct ", hyphens)
        elif accessDtotal<dataTotal:
            print(account, " Missing Ds in Access in REQ# column: ", hyphens)
        elif accessDtotal>dataTotal:
            print(account, " account likely has too many D in REQ column: ", hyphens)
        else:
            print(account, "Error likely happened on account: ", hyphens) #Note: This should never happen
print("------Completed Section 2--------")
print("Done. Finished comparing Access with data in ", round(time.time()-start, 3), " seconds")

1234411999999999120000  account likely has too many D in REQ column:  12344-11-999999999-120000
1234411999999999550000  account likely has too many D in REQ column:  12344-11-999999999-550000
1234411999999999900000  account likely has too many D in REQ column:  12344-11-999999999-900000
5555555555555555555555  Missing Ds in Access in REQ# column:  55555-55-555555555-555555
------Completed Section 2--------
Done. Finished comparing Access with data in  3.331  seconds

## Special Notes
Line 80 Special Note: The only reason I add back the hyphens is so an accounting assistant can easily copy/paste the account number into a database to retrieve the records. Otherwise, the individual would have to type out the full account number by hand and/or could possibly accidently type the wrong account number. This not only saves time but also makes the work of the accountant more enjoyable.

## Diclosure
ACCOUNTING AUTOMATION SHOULD NEVER REPLACE AN ACCOUNTANT, CPA OR FINANCIAL ADVISOR: <br>
Python can work at instant speeds to detect new transactions, human error, transpoisitional errors, or missing transactions. It may not detect every error, fraud, or have the mindset of a human. However, Python can help with the following:
1. Compare thousands of transactions between actual processed transactions and accounting books. Are the accounting subtotals balanced?
2. New transactions that have been posted or changed. Has a new transaction been posted? Has an old transaction not been recorded?
3. Finding a transpositional error. Was a transaction recorded as 3832.12 but was actually 3823.12? This is difficult to see with the human eye when there are thousands of transactions.
4. Calculating all possible subtotals. How did our potentially ending balance end at XX.XX?