# Date Report

#### Enter the Dates to Generate Report

In [1]:
date1='7/01/2021'
date2='9/30/2021'
dept='Food'

#### Change Nothing Below:

In [2]:
import numpy as np 
import pandas as pd 
import os
from datetime import datetime
import time

start=time.time()
date=datetime.today().strftime('%m-%d-%Y')
print("Running Reggie Report on: ", date)

file=r'/kaggle/input/datareport/dataReport.csv'
df=pd.read_csv(file)
df.head()

Running Reggie Report on:  08-10-2022

,GL Account,GL Description,Date,Source,Reference Number,Description,Opening Balance,YTD Debits,YTD Credits
0,315,CR,5/10/2022,REGGIE,12345,ReggieRules,NaN,2386,NaN
1,473,CR,3/19/2022,REGGIE,12346,ReggieRules,NaN,2819,NaN
2,266,CR,8/7/2021,REGGIE,12347,ReggieRules,NaN,1041,NaN
3,530,CR,6/21/2022,REGGIE,12348,ReggieRules,NaN,2378,NaN
4,545,CR,7/25/2021,REGGIE,12349,ReggieRules,NaN,1588,NaN

In [3]:
df=df[['GL Account', ' Date', ' YTD Debits', ' YTD Credits']]
df.head()

   GL Account       Date   YTD Debits   YTD Credits
0         315  5/10/2022         2386           NaN
1         473  3/19/2022         2819           NaN
2         266   8/7/2021         1041           NaN
3         530  6/21/2022         2378           NaN
4         545  7/25/2021         1588           NaN

In [4]:
df[[' YTD Debits', ' YTD Credits']]=df[[' YTD Debits', ' YTD Credits']].fillna(0)
df.head()

   GL Account       Date   YTD Debits   YTD Credits
0         315  5/10/2022         2386           0.0
1         473  3/19/2022         2819           0.0
2         266   8/7/2021         1041           0.0
3         530  6/21/2022         2378           0.0
4         545  7/25/2021         1588           0.0

In [5]:
df['DataTotal'] = df.apply((lambda x: x[' YTD Debits'] - x[' YTD Credits']), axis=1)
df.head()

   GL Account       Date   YTD Debits   YTD Credits  DataTotal
0         315  5/10/2022         2386           0.0     2386.0
1         473  3/19/2022         2819           0.0     2819.0
2         266   8/7/2021         1041           0.0     1041.0
3         530  6/21/2022         2378           0.0     2378.0
4         545  7/25/2021         1588           0.0     1588.0

In [6]:
df=df.drop(columns=[' YTD Debits', ' YTD Credits'])
df.head()

   GL Account       Date  DataTotal
0         315  5/10/2022     2386.0
1         473  3/19/2022     2819.0
2         266   8/7/2021     1041.0
3         530  6/21/2022     2378.0
4         545  7/25/2021     1588.0

In [7]:
df=df.groupby(['GL Account', ' Date'])['DataTotal'].sum().reset_index()
df.head()

   GL Account        Date  DataTotal
0         222  10/11/2021      658.0
1         222  11/20/2021     3251.0
2         222  11/22/2021     3260.0
3         222  12/21/2021     1950.0
4         222   2/19/2022     3761.0

In [8]:
df=df[(df[' Date'] > date1) & (df[' Date'] < date2)].reset_index()
df.head()

   index  GL Account       Date  DataTotal
0      6         222  8/13/2021      508.0
1     11         223  7/20/2021     3295.0
2     12         223   7/6/2021     1808.0
3     18         224  7/27/2021     3739.0
4     19         224  8/12/2021     3685.0

In [9]:
df=df.groupby(['GL Account'])['DataTotal'].sum().reset_index()
df.head(1000)

     GL Account  DataTotal
0           222      508.0
1           223     5103.0
2           224     7424.0
3           225     3146.0
4           226     3740.0
..          ...        ...
273         551     3345.0
274         552     7771.0
275         553    11709.0
276         554      588.0
277         555     5423.0

[278 rows x 2 columns]

In [10]:
df1=df[(df['GL Account'] > 200) & (df['GL Account'] < 300)]
df1.head()

   GL Account  DataTotal
0         222      508.0
1         223     5103.0
2         224     7424.0
3         225     3146.0
4         226     3740.0

In [11]:
df2=df[(df['GL Account'] > 300) & (df['GL Account'] < 400)]
df2.head()

    GL Account  DataTotal
67         301     6322.0
68         302      736.0
69         303      354.0
70         304     6899.0
71         305     3635.0

In [12]:
df3=df[(df['GL Account'] > 400) & (df['GL Account'] < 500)]
df3=df3.style.set_caption("Hello World")
df3

In [13]:
#df1=df1.style.set_table_attributes("style='display:inline'").set_caption('Campus Rec Q1')

In [14]:
#import openpyxl
#df=df.style.hide_index()

#df.to_excel("Q1Report.xlsx", index=None)
#print("Your submission was successfully saved!")

In [15]:
'''
import xlsxwriter

text1 = "Department: "+ dept
text2 = "Between dates "+ date1 + " and "+ date2

writer = pd.ExcelWriter('output.xlsx', engine='xlsxwriter')

# Write each dataframe to a different worksheet.
df1.to_excel(writer, sheet_name='SFC', startrow=3, startcol=2, header=True, index=False)
df2.to_excel(writer, sheet_name='BBC', startrow=3, startcol=2, header=True, index=False)
df3.to_excel(writer, sheet_name='ADV', startrow=3, startcol=2, header=True, index=False)


worksheet1 = writer.sheets['SFC']
worksheet2 = writer.sheets['BBC']
worksheet3 = writer.sheets['ADV']

#Write to each worksheet:
worksheet1.write(0, 0, text1)
worksheet1.write(1, 0, text2)
worksheet2.write(0, 0, text1)
worksheet2.write(1, 0, text2)
worksheet3.write(0, 0, text1)
worksheet3.write(1, 0, text2)

# Close the Pandas Excel writer and output the Excel file.
writer.save()
print("Done")
'''

'\nimport xlsxwriter\n\ntext1 = "Department: "+ dept\ntext2 = "Between dates "+ date1 + " and "+ date2\n\nwriter = pd.ExcelWriter(\'output.xlsx\', engine=\'xlsxwriter\')\n\n# Write each dataframe to a different worksheet.\ndf1.to_excel(writer, sheet_name=\'SFC\', startrow=3, startcol=2, header=True, index=False)\ndf2.to_excel(writer, sheet_name=\'BBC\', startrow=3, startcol=2, header=True, index=False)\ndf3.to_excel(writer, sheet_name=\'ADV\', startrow=3, startcol=2, header=True, index=False)\n\n\nworksheet1 = writer.sheets[\'SFC\']\nworksheet2 = writer.sheets[\'BBC\']\nworksheet3 = writer.sheets[\'ADV\']\n\n#Write to each worksheet:\nworksheet1.write(0, 0, text1)\nworksheet1.write(1, 0, text2)\nworksheet2.write(0, 0, text1)\nworksheet2.write(1, 0, text2)\nworksheet3.write(0, 0, text1)\nworksheet3.write(1, 0, text2)\n\n# Close the Pandas Excel writer and output the Excel file.\nwriter.save()\nprint("Done")\n'

In [16]:
print("Done. Finished in ", round((time.time()-start), 4), " seconds")

Done. Finished in  0.5861  seconds