## Data

In [1]:
import pandas as pd

account = ['9040608', '9040608', '1235508', '6464typo']
voucher = ['V1234', 'V1235','V1236', 'V1237']
posted = ['Y', 'Y', 'Y', 'N']
total = [631.2, 601.3, 721.3, 722.4]

data = {'Account': account,
       'Voucher':voucher,
       'Posted':posted,
       'Total':total}

data = pd.DataFrame(data)
data.head()

    Account Voucher Posted  Total
0   9040608   V1234      Y  631.2
1   9040608   V1235      Y  601.3
2   1235508   V1236      Y  721.3
3  6464typo   V1237      N  722.4

In [2]:
Aaccount = ['90406-08','90406-08', '90406-08', '12355-08', '64644-08']
Avoucher = ['V1233','V1234', 'V1235','V1236', 'V1237']
Aposted = ['Y','Y', 'Y', 'Y', 'N']
Atotal = [3031.67, 631.2, 601.3, 731.3, 722.4]

access = {'aAccount': Aaccount,
       'aVoucher':Avoucher,
       'aPosted':Aposted,
       'aTotal': Atotal}

access = pd.DataFrame(access)
access

   aAccount aVoucher aPosted   aTotal
0  90406-08    V1233       Y  3031.67
1  90406-08    V1234       Y   631.20
2  90406-08    V1235       Y   601.30
3  12355-08    V1236       Y   731.30
4  64644-08    V1237       N   722.40

In [3]:
df=data[['Account','Total', 'Posted']]
df.head()

    Account  Total Posted
0   9040608  631.2      Y
1   9040608  601.3      Y
2   1235508  721.3      Y
3  6464typo  722.4      N

In [4]:
df=df.loc[df['Posted'] == 'Y']
df.head()

   Account  Total Posted
0  9040608  631.2      Y
1  9040608  601.3      Y
2  1235508  721.3      Y

In [5]:
df=df.groupby(['Account'])['Total'].sum().reset_index()
df.head()

   Account   Total
0  1235508   721.3
1  9040608  1232.5

In [6]:
access = access.replace('-', '', regex=True)
access.head()

  aAccount aVoucher aPosted   aTotal
0  9040608    V1233       Y  3031.67
1  9040608    V1234       Y   631.20
2  9040608    V1235       Y   601.30
3  1235508    V1236       Y   731.30
4  6464408    V1237       N   722.40

In [7]:
access=access.groupby(['aAccount'])['aTotal'].sum().reset_index()
access.head()

  aAccount   aTotal
0  1235508   731.30
1  6464408   722.40
2  9040608  4264.17

In [8]:
accounts=df['Account']
for a in accounts:
    print(a)

1235508
9040608