# Quarterly Report GLBA

# Current Quarter Data

In [1]:
import pandas as pd
data1=r'/kaggle/input/glbaqrt/GLBA.csv'
data1=pd.read_csv(data1)
data1.head()

,GL Account,GL Description,Allocated Budget,Actual,% Used,Available,Budget Officer
0,2470650,REGGIE,0,823.00,0.0,-823.00,1234567
1,2470850,REGGIE,0,35.00,0.0,-35.00,1234567
2,2471050,REGGIE,0,-438252.78,0.0,438252.78,1234567
3,2471250,REGGIE,0,0.00,0.0,0.00,1234567
4,2471450,REGGIE,0,-185.10,0.0,185.10,1234567

In [2]:
from babel.numbers import format_currency

data1=data1[['GL Account', 'GL Description', 'Allocated Budget', 'Actual', '% Used']].fillna(0)
data1.rename(columns={'Allocated Budget': 'Budget', 'GL Description': 'Revenue'}, inplace=True)
data1.insert(5, " . ", " ") 

#CURRENCY:
#data["Budget"] = data["Budget"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
#data["Actual"] = data["Actual"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
#data['% Used'] = data['% Used'].apply(lambda x: "{0:.2f}%".format(x*100))
data1.head()

   GL Account Revenue  Budget     Actual  % Used  .
0     2470650  REGGIE       0     823.00     0.0
1     2470850  REGGIE       0      35.00     0.0
2     2471050  REGGIE       0 -438252.78     0.0
3     2471250  REGGIE       0       0.00     0.0
4     2471450  REGGIE       0    -185.10     0.0

# Previous Year Data

In [3]:
#READ PREVIOUS QRT DATA:
data2=r'/kaggle//input/glbaq1/GLBA1.csv'
data2=pd.read_csv(data2)
data2=data2[['GL Account', 'Allocated Budget', 'Actual', '% Used']].fillna(0)
data2.head()

   GL Account  Allocated Budget     Actual  % Used
0     2470650                 0     100.00     0.0
1     2470850                 0      80.00     0.0
2     2471050                 0 -438252.78     0.0
3     2471250                 0       0.00     0.0
4     2471450                 0    -385.10     0.0

#### Rename Columns

In [4]:
data2.rename(columns={'Allocated Budget': 'Budget1', 'Actual': 'Actual1','% Used': '% Used1'}, inplace=True)

#CHANGE CURRENCY:
#data2["Budget1"] = data2["Budget1"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
#data2["Actual1"] = data2["Actual1"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
#data2['% Used1'] = data2['% Used1'].apply(lambda x: "{0:.2f}%".format(x*100))
data2.head()

   GL Account  Budget1    Actual1  % Used1
0     2470650        0     100.00      0.0
1     2470850        0      80.00      0.0
2     2471050        0 -438252.78      0.0
3     2471250        0       0.00      0.0
4     2471450        0    -385.10      0.0

# Join Data with Previous Year Data

In [5]:
data=data1.merge(data2, on='GL Account')
data.head()

,GL Account,Revenue,Budget,Actual,% Used,.,Budget1,Actual1,% Used1
0,2470650,REGGIE,0,823.00,0.0,,0,100.00,0.0
1,2470850,REGGIE,0,35.00,0.0,,0,80.00,0.0
2,2471050,REGGIE,0,-438252.78,0.0,,0,-438252.78,0.0
3,2471250,REGGIE,0,0.00,0.0,,0,0.00,0.0
4,2471450,REGGIE,0,-185.10,0.0,,0,-385.10,0.0

In [6]:
data=data.rename(columns={'GL Account':'Object Code'}).reset_index(drop=True)
data.head()

,Object Code,Revenue,Budget,Actual,% Used,.,Budget1,Actual1,% Used1
0,2470650,REGGIE,0,823.00,0.0,,0,100.00,0.0
1,2470850,REGGIE,0,35.00,0.0,,0,80.00,0.0
2,2471050,REGGIE,0,-438252.78,0.0,,0,-438252.78,0.0
3,2471250,REGGIE,0,0.00,0.0,,0,0.00,0.0
4,2471450,REGGIE,0,-185.10,0.0,,0,-385.10,0.0

# Split Revenue and Expense

In [7]:
data['dept']  =   data['Object Code'].astype(str).str[:-3].astype(int)
data['Object Code']  = data['Object Code'].astype(str).str[-3:].astype(int)
data.head()

,Object Code,Revenue,Budget,Actual,% Used,.,Budget1,Actual1,% Used1,dept
0,650,REGGIE,0,823.00,0.0,,0,100.00,0.0,2470
1,850,REGGIE,0,35.00,0.0,,0,80.00,0.0,2470
2,50,REGGIE,0,-438252.78,0.0,,0,-438252.78,0.0,2471
3,250,REGGIE,0,0.00,0.0,,0,0.00,0.0,2471
4,450,REGGIE,0,-185.10,0.0,,0,-385.10,0.0,2471

In [8]:
revDF=data[data['Object Code'] < 600].sort_values(by='Object Code')
revDF.head()

,Object Code,Revenue,Budget,Actual,% Used,.,Budget1,Actual1,% Used1,dept
2,50,REGGIE,0,-438252.78,0.0,,0,-438252.78,0.0,2471
47,50,REGGIE,0,0.00,0.0,,0,0.00,0.0,2480
37,50,REGGIE,0,-49.00,0.0,,0,-49.00,0.0,2478
32,50,REGGIE,0,-1739.58,0.0,,0,-1739.58,0.0,2477
27,50,REGGIE,0,-7480.75,0.0,,0,-7480.75,0.0,2476

In [9]:
expDF=data[data['Object Code']>600].sort_values(by='Object Code')
expDF = expDF.rename(columns={'Revenue': 'Expenses'})
expDF.head()

,Object Code,Expenses,Budget,Actual,% Used,.,Budget1,Actual1,% Used1,dept
0,650,REGGIE,0,823.00,0.0,,0,100.00,0.0,2470
55,650,REGGIE,0,-200.00,0.0,,0,-200.00,0.0,2481
50,650,REGGIE,26200,9039.56,34.5,,26200,9039.56,34.5,2480
45,650,REGGIE,0,0.00,0.0,,0,0.00,0.0,2479
40,650,REGGIE,0,0.00,0.0,,0,0.00,0.0,2478

# Create New Tabs by Dept

In [10]:
import warnings
warnings.filterwarnings("ignore")

intCols=['Budget','Actual', '% Used', 'Budget1', 'Actual1', '% Used1']
revDF1=revDF[(revDF['dept'] ==2471)]
revDF1.loc['Total Income']= revDF1[intCols].sum()

revDF1["Budget"] = revDF1["Budget"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
revDF1["Budget1"] = revDF1["Budget1"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
revDF1["Actual"] = revDF1["Actual"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
revDF1["Actual1"] = revDF1["Actual1"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
#df1['% Used1'] = df1['% Used1'].apply(lambda x: "{0:.2f}%".format(x*100))
revDF1.head()

,Object Code,Revenue,Budget,Actual,% Used,.,Budget1,Actual1,% Used1,dept
2,50.0,REGGIE,$0.00,"-$438,252.78",0.0,,$0.00,"-$438,252.78",0.0,2471.0
3,250.0,REGGIE,$0.00,$0.00,0.0,,$0.00,$0.00,0.0,2471.0
4,450.0,REGGIE,$0.00,-$185.10,0.0,,$0.00,-$385.10,0.0,2471.0
Total Income,NaN,NaN,$0.00,"-$438,437.88",0.0,NaN,$0.00,"-$438,637.88",0.0,NaN

In [11]:
expDF1=expDF[(expDF['dept'] ==2471)]
expDF1.loc['Total Income']= expDF1[intCols].sum()
expDF1.head()

,Object Code,Expenses,Budget,Actual,% Used,.,Budget1,Actual1,% Used1,dept
5,650.0,REGGIE,0.0,-626490.00,0.00,,0.0,-426490.00,0.00,2471.0
6,850.0,REGGIE,162931.0,54139.75,33.23,,262931.0,34139.75,33.23,2471.0
Total Income,NaN,NaN,162931.0,-572350.25,33.23,NaN,262931.0,-392350.25,33.23,NaN

In [12]:
df2=revDF[(revDF['dept']==2472)].reset_index(drop=True)
df2.loc['Total Income']= df2[intCols].sum()
df2.head()

,Object Code,Revenue,Budget,Actual,% Used,.,Budget1,Actual1,% Used1,dept
0,50.0,REGGIE,970602.0,300339.75,30.94,,470602.0,100339.75,34.94,2472.0
1,250.0,REGGIE,0.0,-10.00,0.00,,0.0,-10.00,0.00,2472.0
2,450.0,REGGIE,0.0,-50.00,0.00,,0.0,-50.00,0.00,2472.0
Total Income,NaN,NaN,970602.0,300279.75,30.94,NaN,470602.0,100279.75,34.94,NaN

In [13]:
df3=revDF[(revDF['dept'] == 2473)]
df3.loc['Total Income']= revDF[intCols].sum()
df3.head()

,Object Code,Revenue,Budget,Actual,% Used,.,Budget1,Actual1,% Used1,dept
12,50.0,REGGIE,0.0,0.00,0.00,,0.0,0.00,0.00,2473.0
13,250.0,REGGIE,10218.0,2675.47,26.18,,10218.0,2675.47,26.18,2473.0
14,450.0,REGGIE,12289.0,2455.64,19.98,,12289.0,2455.64,19.98,2473.0
Total Income,NaN,NaN,1198168.0,-87577.20,551.51,NaN,698168.0,-287777.20,555.51,NaN

# Creating Final Report

In [14]:
'''
#!pip install xlsxwriter
import xlsxwriter

fileName='Campus.xlsx'
year='FY22'
pYear='FY21'
header=year+' - Q3 Financials as of 5/11/22'
ag='Agency SFC'
bbc='Bond BBC'
sfcBond='BOND SFC'
startrow=4
startcol=1

#CHANGE NOTHING BELOW:
writer = pd.ExcelWriter(fileName, engine='xlsxwriter')
workbook  = writer.book

header_format = workbook.add_format( 
    {
        'bold': True,
        'text_wrap': False,
        'valign': 'left',
        # 'fg_color': '#D7E4BC',
        #'bg_color': '#edbd93',
        #'border': 1
    }
)

bold = workbook.add_format( 
    {
        'bold': True,
        'text_wrap': False,
        'valign': 'center',
    }
)

import seaborn as sns
cm = sns.light_palette("red", as_cmap=True)

revDF1s=revDF1.style.background_gradient(axis=None, low=0, high=.4, subset=['% Used'], cmap=cm).set_properties(**{'border': '1px black solid !important','color':'black', 'border-width':'1px'}).hide_index()
expDF1s=expDF1.style.background_gradient(axis=None, low=0, high=.4, subset=['% Used'], cmap=cm).set_properties(**{'border': '1px black solid !important','color':'black', 'border-width':'1px'}).hide_index()
df2=df2.style.background_gradient(axis=None, low=0, high=.4, subset=['% Used'], cmap=cm).set_properties(**{'border': '1px black solid !important','color':'black', 'border-width':'1px'}).hide_index()
df3=df3.style.background_gradient(axis=None, low=0, high=.4, subset=['% Used'], cmap=cm).set_properties(**{'border': '1px black solid !important','color':'black', 'border-width':'1px'}).hide_index()
'''

'\n#!pip install xlsxwriter\nimport xlsxwriter\n\nfileName=\'Campus.xlsx\'\nyear=\'FY22\'\npYear=\'FY21\'\nheader=year+\' - Q3 Financials as of 5/11/22\'\nag=\'Agency SFC\'\nbbc=\'Bond BBC\'\nsfcBond=\'BOND SFC\'\nstartrow=4\nstartcol=1\n\n#CHANGE NOTHING BELOW:\nwriter = pd.ExcelWriter(fileName, engine=\'xlsxwriter\')\nworkbook  = writer.book\n\nheader_format = workbook.add_format( \n    {\n        \'bold\': True,\n        \'text_wrap\': False,\n        \'valign\': \'left\',\n        # \'fg_color\': \'#D7E4BC\',\n        #\'bg_color\': \'#edbd93\',\n        #\'border\': 1\n    }\n)\n\nbold = workbook.add_format( \n    {\n        \'bold\': True,\n        \'text_wrap\': False,\n        \'valign\': \'center\',\n    }\n)\n\nimport seaborn as sns\ncm = sns.light_palette("red", as_cmap=True)\n\nrevDF1s=revDF1.style.background_gradient(axis=None, low=0, high=.4, subset=[\'% Used\'], cmap=cm).set_properties(**{\'border\': \'1px black solid !important\',\'color\':\'black\', \'border-width\':\'1px\'}).hide_index()\nexpDF1s=expDF1.style.background_gradient(axis=None, low=0, high=.4, subset=[\'% Used\'], cmap=cm).set_properties(**{\'border\': \'1px black solid !important\',\'color\':\'black\', \'border-width\':\'1px\'}).hide_index()\ndf2=df2.style.background_gradient(axis=None, low=0, high=.4, subset=[\'% Used\'], cmap=cm).set_properties(**{\'border\': \'1px black solid !important\',\'color\':\'black\', \'border-width\':\'1px\'}).hide_index()\ndf3=df3.style.background_gradient(axis=None, low=0, high=.4, subset=[\'% Used\'], cmap=cm).set_properties(**{\'border\': \'1px black solid !important\',\'color\':\'black\', \'border-width\':\'1px\'}).hide_index()\n'

#### Generate Report

In [15]:
'''
#AGENCY:
revDF1s.to_excel(writer, sheet_name=ag, startrow=startrow, startcol=startcol)
expDF1s.to_excel(writer, sheet_name=ag, startrow=startrow+len(revDF1)+1, startcol=startcol)

worksheet1 = writer.sheets[ag]
worksheet1.write(1, 0, 'Campus '+ ag, header_format)
worksheet1.write(2, 0, header, header_format)
worksheet1.write(3, 4, year, bold)
worksheet1.write(3, 9, pYear, bold)

#BBC:
df2.to_excel(writer, sheet_name=bbc, startrow=startrow, startcol=startcol)
worksheet2 = writer.sheets[bbc]
worksheet2.write(1, 0, 'Campus '+ bbc, header_format)
worksheet2.write(2, 0, header, header_format)
worksheet2.write(3, 4, year, bold)
worksheet2.write(3, 9, pYear, bold)

#ADV:
df3.to_excel(writer, sheet_name=sfcBond, startrow=startrow, startcol=startcol)
worksheet3 = writer.sheets[sfcBond]
worksheet3.write(1, 0, 'Campus '+ sfcBond, header_format)
worksheet3.write(2, 0, header, header_format)
worksheet3.write(3, 4, year, bold)
worksheet3.write(3, 9, pYear, bold)

#SAVE SHEET:
writer.save()
print("New Excel Report File created: ", fileName)
'''

'\n#AGENCY:\nrevDF1s.to_excel(writer, sheet_name=ag, startrow=startrow, startcol=startcol)\nexpDF1s.to_excel(writer, sheet_name=ag, startrow=startrow+len(revDF1)+1, startcol=startcol)\n\nworksheet1 = writer.sheets[ag]\nworksheet1.write(1, 0, \'Campus \'+ ag, header_format)\nworksheet1.write(2, 0, header, header_format)\nworksheet1.write(3, 4, year, bold)\nworksheet1.write(3, 9, pYear, bold)\n\n#BBC:\ndf2.to_excel(writer, sheet_name=bbc, startrow=startrow, startcol=startcol)\nworksheet2 = writer.sheets[bbc]\nworksheet2.write(1, 0, \'Campus \'+ bbc, header_format)\nworksheet2.write(2, 0, header, header_format)\nworksheet2.write(3, 4, year, bold)\nworksheet2.write(3, 9, pYear, bold)\n\n#ADV:\ndf3.to_excel(writer, sheet_name=sfcBond, startrow=startrow, startcol=startcol)\nworksheet3 = writer.sheets[sfcBond]\nworksheet3.write(1, 0, \'Campus \'+ sfcBond, header_format)\nworksheet3.write(2, 0, header, header_format)\nworksheet3.write(3, 4, year, bold)\nworksheet3.write(3, 9, pYear, bold)\n\n#SAVE SHEET:\nwriter.save()\nprint("New Excel Report File created: ", fileName)\n'

# Sources
1.  https://stackoverflow.com/questions/59794843/xlsxwriter-error-attributeerror-workbook-object-has-no-attribute-add-format