# Quarterly Report GLBA

# Current Quarter Data

In [1]:
import pandas as pd
data=r'/kaggle/input/glbaqrt/GLBA.csv'
data=pd.read_csv(data)
data.head()

,GL Account,GL Description,Allocated Budget,Actual,% Used,Available,Budget Officer
0,2470650,REGGIE,0,823.00,0.0,-823.00,1234567
1,2470850,REGGIE,0,35.00,0.0,-35.00,1234567
2,2471050,REGGIE,0,-438252.78,0.0,438252.78,1234567
3,2471250,REGGIE,0,0.00,0.0,0.00,1234567
4,2471450,REGGIE,0,-185.10,0.0,185.10,1234567

In [2]:
from babel.numbers import format_currency

data=data[['GL Account', 'GL Description', 'Allocated Budget', 'Actual', '% Used']].fillna(0)
data.rename(columns={'Allocated Budget': 'Budget', 'GL Description': 'Revenue'}, inplace=True)
data.insert(5, " . ", " ") 

#CURRENCY:
#data["Budget"] = data["Budget"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
#data["Actual"] = data["Actual"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
#data['% Used'] = data['% Used'].apply(lambda x: "{0:.2f}%".format(x*100))
data.head()

   GL Account Revenue  Budget     Actual  % Used  .
0     2470650  REGGIE       0     823.00     0.0
1     2470850  REGGIE       0      35.00     0.0
2     2471050  REGGIE       0 -438252.78     0.0
3     2471250  REGGIE       0       0.00     0.0
4     2471450  REGGIE       0    -185.10     0.0

# Previous Year Data

In [3]:
#READ PREVIOUS QRT DATA:
data2=r'/kaggle//input/glbaq1/GLBA1.csv'
data2=pd.read_csv(data2)
data2=data2[['GL Account', 'Allocated Budget', 'Actual', '% Used']].fillna(0)
data2.head()

   GL Account  Allocated Budget     Actual  % Used
0     2470650                 0     100.00     0.0
1     2470850                 0      80.00     0.0
2     2471050                 0 -438252.78     0.0
3     2471250                 0       0.00     0.0
4     2471450                 0    -385.10     0.0

#### Rename Columns

In [4]:
data2.rename(columns={'Allocated Budget': 'Budget1', 'Actual': 'Actual1','% Used': '% Used1'}, inplace=True)

#CHANGE CURRENCY:
#data2["Budget1"] = data2["Budget1"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
#data2["Actual1"] = data2["Actual1"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
#data2['% Used1'] = data2['% Used1'].apply(lambda x: "{0:.2f}%".format(x*100))
data2.head()

   GL Account  Budget1    Actual1  % Used1
0     2470650        0     100.00      0.0
1     2470850        0      80.00      0.0
2     2471050        0 -438252.78      0.0
3     2471250        0       0.00      0.0
4     2471450        0    -385.10      0.0

# Join Data with Previous Year Data

In [5]:
revDF=data.merge(data2, on='GL Account')
revDF.head()

,GL Account,Revenue,Budget,Actual,% Used,.,Budget1,Actual1,% Used1
0,2470650,REGGIE,0,823.00,0.0,,0,100.00,0.0
1,2470850,REGGIE,0,35.00,0.0,,0,80.00,0.0
2,2471050,REGGIE,0,-438252.78,0.0,,0,-438252.78,0.0
3,2471250,REGGIE,0,0.00,0.0,,0,0.00,0.0
4,2471450,REGGIE,0,-185.10,0.0,,0,-385.10,0.0

In [6]:
revDF=revDF.rename(columns={'GL Account':'Object Code'}).reset_index(drop=True)
revDF.head()

,Object Code,Revenue,Budget,Actual,% Used,.,Budget1,Actual1,% Used1
0,2470650,REGGIE,0,823.00,0.0,,0,100.00,0.0
1,2470850,REGGIE,0,35.00,0.0,,0,80.00,0.0
2,2471050,REGGIE,0,-438252.78,0.0,,0,-438252.78,0.0
3,2471250,REGGIE,0,0.00,0.0,,0,0.00,0.0
4,2471450,REGGIE,0,-185.10,0.0,,0,-385.10,0.0

# Split Revenue and Expense

In [7]:
revDF['dept']  =   revDF['Object Code'].astype(str).str[:-3].astype(int)
revDF['Object Code']  = revDF['Object Code'].astype(str).str[-3:].astype(int)
revDF.head()

,Object Code,Revenue,Budget,Actual,% Used,.,Budget1,Actual1,% Used1,dept
0,650,REGGIE,0,823.00,0.0,,0,100.00,0.0,2470
1,850,REGGIE,0,35.00,0.0,,0,80.00,0.0,2470
2,50,REGGIE,0,-438252.78,0.0,,0,-438252.78,0.0,2471
3,250,REGGIE,0,0.00,0.0,,0,0.00,0.0,2471
4,450,REGGIE,0,-185.10,0.0,,0,-385.10,0.0,2471

In [8]:
revDF=revDF[revDF['Object Code']> 500]
revDF.head()

,Object Code,Revenue,Budget,Actual,% Used,.,Budget1,Actual1,% Used1,dept
0,650,REGGIE,0,823.00,0.00,,0,100.00,0.00,2470
1,850,REGGIE,0,35.00,0.00,,0,80.00,0.00,2470
5,650,REGGIE,0,-626490.00,0.00,,0,-426490.00,0.00,2471
6,850,REGGIE,162931,54139.75,33.23,,262931,34139.75,33.23,2471
10,650,REGGIE,0,-10.00,0.00,,0,-10.00,0.00,2472

# Create New Tabs by Dept

In [9]:
import warnings
warnings.filterwarnings("ignore")

intCols=['Budget','Actual', '% Used', 'Budget1', 'Actual1', '% Used1']
df1=revDF[(revDF['dept'] ==2471)]
df1.loc['Total Income']= df1[intCols].sum()
df1["Budget"] = df1["Budget"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
df1["Budget1"] = df1["Budget1"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
df1["Actual"] = df1["Actual"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
df1["Actual1"] = df1["Actual1"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
#df1['% Used1'] = df1['% Used1'].apply(lambda x: "{0:.2f}%".format(x*100))
df1.head()

,Object Code,Revenue,Budget,Actual,% Used,.,Budget1,Actual1,% Used1,dept
5,650.0,REGGIE,$0.00,"-$626,490.00",0.00,,$0.00,"-$426,490.00",0.00,2471.0
6,850.0,REGGIE,"$162,931.00","$54,139.75",33.23,,"$262,931.00","$34,139.75",33.23,2471.0
Total Income,NaN,NaN,"$162,931.00","-$572,350.25",33.23,NaN,"$262,931.00","-$392,350.25",33.23,NaN

In [10]:
df2=revDF[(revDF['dept']==2472)]
df2.loc['Total Income']= df2[intCols].sum()
df2.head()

,Object Code,Revenue,Budget,Actual,% Used,.,Budget1,Actual1,% Used1,dept
10,650.0,REGGIE,0.0,-10.00,0.00,,0.0,-10.00,0.00,2472.0
11,850.0,REGGIE,13929.0,3605.64,25.89,,13929.0,3605.64,25.89,2472.0
Total Income,NaN,NaN,13929.0,3595.64,25.89,NaN,13929.0,3595.64,25.89,NaN

In [11]:
df3=revDF[(revDF['dept'] == 2473)]
df3.loc['Total Income']= revDF[intCols].sum()
df3.head()

,Object Code,Revenue,Budget,Actual,% Used,.,Budget1,Actual1,% Used1,dept
15,650.0,REGGIE,0.0,-130.00,0.00,,0.0,-130.00,0.00,2473.0
16,850.0,REGGIE,0.0,-23362.79,0.00,,0.0,-23362.79,0.00,2473.0
Total Income,NaN,NaN,357265.0,-783098.15,131.75,NaN,457265.0,-603776.15,131.75,NaN

# Final Excel Created

In [12]:
'''
#!pip install xlsxwriter
import xlsxwriter

fileName='Campus.xlsx'
year='FY22'
pYear='FY21'
header=year+' - Q3 Financials as of 5/11/22'
ag='Agency SFC'
bbc='Bond BBC'
sfcBond='BOND SFC'
startrow=4
startcol=1

#CHANGE NOTHING BELOW:
writer = pd.ExcelWriter(fileName, engine='xlsxwriter')

workbook  = writer.book

header_format = workbook.add_format( 
    {
        'bold': True,
        'text_wrap': False,
        'valign': 'left',
        # 'fg_color': '#D7E4BC',
        #'bg_color': '#edbd93',
        #'border': 1
    }
)

bold = workbook.add_format( 
    {
        'bold': True,
        'text_wrap': False,
        'valign': 'center',
    }
)

#AGENCY:
df1.to_excel(writer, sheet_name=ag, startrow=startrow, startcol=startcol)
worksheet1 = writer.sheets[ag]
worksheet1.write(1, 0, 'Campus '+ ag, header_format)
worksheet1.write(2, 0, header, header_format)
worksheet1.write(3, 4, year, bold)
worksheet1.write(3, 9, pYear, bold)

#BBC:
df2.to_excel(writer, sheet_name=bbc, startrow=startrow, startcol=startcol)
worksheet2 = writer.sheets[bbc]
worksheet2.write(1, 0, 'Campus '+ bbc, header_format)
worksheet2.write(2, 0, header, header_format)
worksheet2.write(3, 4, year, bold)
worksheet2.write(3, 9, pYear, bold)

#ADV:
df3.to_excel(writer, sheet_name=sfcBond, startrow=startrow, startcol=startcol)
worksheet3 = writer.sheets[sfcBond]
worksheet3.write(1, 0, 'Campus '+ sfcBond, header_format)
worksheet3.write(2, 0, header, header_format)
worksheet3.write(3, 4, year, bold)
worksheet3.write(3, 9, pYear, bold)

#SAVE SHEET:
writer.save()
print("New Excel Report File created: ", fileName)
'''

'\n#!pip install xlsxwriter\nimport xlsxwriter\n\nfileName=\'Campus.xlsx\'\nyear=\'FY22\'\npYear=\'FY21\'\nheader=year+\' - Q3 Financials as of 5/11/22\'\nag=\'Agency SFC\'\nbbc=\'Bond BBC\'\nsfcBond=\'BOND SFC\'\nstartrow=4\nstartcol=1\n\n#CHANGE NOTHING BELOW:\nwriter = pd.ExcelWriter(fileName, engine=\'xlsxwriter\')\n\nworkbook  = writer.book\n\nheader_format = workbook.add_format( \n    {\n        \'bold\': True,\n        \'text_wrap\': False,\n        \'valign\': \'left\',\n        # \'fg_color\': \'#D7E4BC\',\n        #\'bg_color\': \'#edbd93\',\n        #\'border\': 1\n    }\n)\n\nbold = workbook.add_format( \n    {\n        \'bold\': True,\n        \'text_wrap\': False,\n        \'valign\': \'center\',\n    }\n)\n\n#AGENCY:\ndf1.to_excel(writer, sheet_name=ag, startrow=startrow, startcol=startcol)\nworksheet1 = writer.sheets[ag]\nworksheet1.write(1, 0, \'Campus \'+ ag, header_format)\nworksheet1.write(2, 0, header, header_format)\nworksheet1.write(3, 4, year, bold)\nworksheet1.write(3, 9, pYear, bold)\n\n#BBC:\ndf2.to_excel(writer, sheet_name=bbc, startrow=startrow, startcol=startcol)\nworksheet2 = writer.sheets[bbc]\nworksheet2.write(1, 0, \'Campus \'+ bbc, header_format)\nworksheet2.write(2, 0, header, header_format)\nworksheet2.write(3, 4, year, bold)\nworksheet2.write(3, 9, pYear, bold)\n\n#ADV:\ndf3.to_excel(writer, sheet_name=sfcBond, startrow=startrow, startcol=startcol)\nworksheet3 = writer.sheets[sfcBond]\nworksheet3.write(1, 0, \'Campus \'+ sfcBond, header_format)\nworksheet3.write(2, 0, header, header_format)\nworksheet3.write(3, 4, year, bold)\nworksheet3.write(3, 9, pYear, bold)\n\n#SAVE SHEET:\nwriter.save()\nprint("New Excel Report File created: ", fileName)\n'

# Sources
* https://stackoverflow.com/questions/59794843/xlsxwriter-error-attributeerror-workbook-object-has-no-attribute-add-format