# Quarterly Report GLBA

# Current Quarter Data

In [1]:
import pandas as pd
data=r'/kaggle/input/glbaqrt/GLBA.csv'
joinDF=pd.read_csv(data)
joinDF.head()

,GL Account,GL Description,Allocated Budget,Actual,% Used,Available,Budget Officer
0,2470650,REGGIE,0,823.00,0.0,-823.00,1234567
1,2470850,REGGIE,0,35.00,0.0,-35.00,1234567
2,2471050,REGGIE,0,-438252.78,0.0,438252.78,1234567
3,2471250,REGGIE,0,0.00,0.0,0.00,1234567
4,2471450,REGGIE,0,-185.10,0.0,185.10,1234567

In [2]:
joinDF=joinDF[['GL Account', 'Allocated Budget', 'Actual', '% Used']].fillna(0)
joinDF.rename(columns={'Allocated Budget': 'Budget'}, inplace=True)
intCols=['Budget','Actual', '% Used', 'Budget1', 'Actual1', '% Used1']
joinDF.head()

   GL Account  Budget     Actual  % Used
0     2470650       0     823.00     0.0
1     2470850       0      35.00     0.0
2     2471050       0 -438252.78     0.0
3     2471250       0       0.00     0.0
4     2471450       0    -185.10     0.0

# Previous Year Data

In [3]:
data2=r'/kaggle//input/glbaq1/GLBA1.csv'
pdf=pd.read_csv(data2)
pDF=pdf[['GL Account', 'Allocated Budget', 'Actual', '% Used']].fillna(0)
pDF.rename(columns={'Allocated Budget': 'Budget1', 'Actual': 'Actual1','% Used': '% Used1'}, inplace=True)
pDF.head()

   GL Account  Budget1    Actual1  % Used1
0     2470650        0     100.00      0.0
1     2470850        0      80.00      0.0
2     2471050        0 -438252.78      0.0
3     2471250        0       0.00      0.0
4     2471450        0    -385.10      0.0

# Join Data with Previous Year Data

In [4]:
joinDF=joinDF.merge(pDF, on='GL Account')
joinDF.head()

   GL Account  Budget     Actual  % Used  Budget1    Actual1  % Used1
0     2470650       0     823.00     0.0        0     100.00      0.0
1     2470850       0      35.00     0.0        0      80.00      0.0
2     2471050       0 -438252.78     0.0        0 -438252.78      0.0
3     2471250       0       0.00     0.0        0       0.00      0.0
4     2471450       0    -185.10     0.0        0    -385.10      0.0

# Create New Tabs

In [5]:
df1=joinDF[(joinDF['GL Account'] > 2_470_000) & (joinDF['GL Account']<2_480_000)]
df1.loc['Total Income']= df1[intCols].sum()
df1.head()

/opt/conda/lib/python3.7/site-packages/pandas/core/indexing.py:723: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)

   GL Account  Budget     Actual  % Used  Budget1    Actual1  % Used1
0   2470650.0     0.0     823.00     0.0      0.0     100.00      0.0
1   2470850.0     0.0      35.00     0.0      0.0      80.00      0.0
2   2471050.0     0.0 -438252.78     0.0      0.0 -438252.78      0.0
3   2471250.0     0.0       0.00     0.0      0.0       0.00      0.0
4   2471450.0     0.0    -185.10     0.0      0.0    -385.10      0.0

In [6]:
df2=joinDF[(joinDF['GL Account'] > 2_450_000) & (joinDF['GL Account'] < 2_490_000)]
df2.loc['Total Income']= df2[intCols].sum()
df2.head()

   GL Account  Budget     Actual  % Used  Budget1    Actual1  % Used1
0   2470650.0     0.0     823.00     0.0      0.0     100.00      0.0
1   2470850.0     0.0      35.00     0.0      0.0      80.00      0.0
2   2471050.0     0.0 -438252.78     0.0      0.0 -438252.78      0.0
3   2471250.0     0.0       0.00     0.0      0.0       0.00      0.0
4   2471450.0     0.0    -185.10     0.0      0.0    -385.10      0.0

In [7]:
df3=joinDF[(joinDF['GL Account'] > 2_480_000) & (joinDF['GL Account'] < 2_490_000)]
df3.loc['Total Income']= joinDF[intCols].sum()
df3.head()

/opt/conda/lib/python3.7/site-packages/pandas/core/indexing.py:723: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)

    GL Account   Budget   Actual  % Used  Budget1  Actual1  % Used1
47   2480050.0      0.0     0.00     0.0      0.0     0.00      0.0
48   2480250.0      0.0 -1192.90     0.0      0.0 -1192.90      0.0
49   2480450.0   4840.0   880.87    18.2   4840.0   880.87     18.2
50   2480650.0  26200.0  9039.56    34.5  26200.0  9039.56     34.5
51   2480850.0      0.0 -6275.00     0.0      0.0 -6275.00      0.0

# Final Excel Created

In [8]:
'''
#!pip install xlsxwriter
import xlsxwriter

fileName='Campus.xlsx'
header='FY22 - Q3 Financials as of 5/11/22'
ag='Agency'
bbc='BBC'
adv='Adventure'
startrow=4
startcol=1

#CHANGE NOTHING BELOW:
writer = pd.ExcelWriter(fileName, engine='xlsxwriter')

#AGENCY:
df1.to_excel(writer, sheet_name=ag, startrow=startrow, startcol=startcol)
worksheet1 = writer.sheets[ag]
worksheet1.write(1, 0, 'Campus '+ ag)
worksheet1.write(2, 0, header)

#BBC:
df2.to_excel(writer, sheet_name=bbc, startrow=startrow, startcol=startcol)
worksheet2 = writer.sheets[bbc]
worksheet2.write(1, 0, 'Campus '+ bbc)
worksheet2.write(2, 0, header)

#ADV:
df3.to_excel(writer, sheet_name=adv, startrow=startrow, startcol=startcol)
worksheet3 = writer.sheets[adv]
worksheet3.write(1, 0, 'Campus '+ adv)
worksheet3.write(2, 0, header)

writer.save()
print("New Excel Report File created: ", fileName)
'''

'\n#!pip install xlsxwriter\nimport xlsxwriter\n\nfileName=\'Campus.xlsx\'\nheader=\'FY22 - Q3 Financials as of 5/11/22\'\nag=\'Agency\'\nbbc=\'BBC\'\nadv=\'Adventure\'\nstartrow=4\nstartcol=1\n\n#CHANGE NOTHING BELOW:\nwriter = pd.ExcelWriter(fileName, engine=\'xlsxwriter\')\n\n#AGENCY:\ndf1.to_excel(writer, sheet_name=ag, startrow=startrow, startcol=startcol)\nworksheet1 = writer.sheets[ag]\nworksheet1.write(1, 0, \'Campus \'+ ag)\nworksheet1.write(2, 0, header)\n\n#BBC:\ndf2.to_excel(writer, sheet_name=bbc, startrow=startrow, startcol=startcol)\nworksheet2 = writer.sheets[bbc]\nworksheet2.write(1, 0, \'Campus \'+ bbc)\nworksheet2.write(2, 0, header)\n\n#ADV:\ndf3.to_excel(writer, sheet_name=adv, startrow=startrow, startcol=startcol)\nworksheet3 = writer.sheets[adv]\nworksheet3.write(1, 0, \'Campus \'+ adv)\nworksheet3.write(2, 0, header)\n\nwriter.save()\nprint("New Excel Report File created: ", fileName)\n'