# Quarterly Report GLBA

In [1]:
import pandas as pd
data=r'/kaggle/input/glbaqrt/GLBA.csv'
df=pd.read_csv(data)
df.head()

,GL Account,GL Description,Allocated Budget,Actual,% Used,Available,Budget Officer
0,2470650,REGGIE,0,823.00,0.0,-823.00,1234567
1,2470850,REGGIE,0,35.00,0.0,-35.00,1234567
2,2471050,REGGIE,0,-438252.78,0.0,438252.78,1234567
3,2471250,REGGIE,0,0.00,0.0,0.00,1234567
4,2471450,REGGIE,0,-185.10,0.0,185.10,1234567

In [2]:
df=df[['GL Account', 'Allocated Budget', 'Actual', '% Used']]
intCols=['Allocated Budget','Actual', '% Used']
df.head()

   GL Account  Allocated Budget     Actual  % Used
0     2470650                 0     823.00     0.0
1     2470850                 0      35.00     0.0
2     2471050                 0 -438252.78     0.0
3     2471250                 0       0.00     0.0
4     2471450                 0    -185.10     0.0

In [3]:
df1=df[(df['GL Account'] > 2_470_000) & (df['GL Account']<2_480_000)]
df1.loc['Total Income']= df1[intCols].sum()
df1.head()

/opt/conda/lib/python3.7/site-packages/pandas/core/indexing.py:723: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)

   GL Account  Allocated Budget     Actual  % Used
0   2470650.0               0.0     823.00     0.0
1   2470850.0               0.0      35.00     0.0
2   2471050.0               0.0 -438252.78     0.0
3   2471250.0               0.0       0.00     0.0
4   2471450.0               0.0    -185.10     0.0

In [4]:
df2=df[(df['GL Account'] > 2_450_000) & (df['GL Account'] < 2_490_000)]
df2.loc['Total Income']= df2[intCols].sum()
df2.head()

   GL Account  Allocated Budget     Actual  % Used
0   2470650.0               0.0     823.00     0.0
1   2470850.0               0.0      35.00     0.0
2   2471050.0               0.0 -438252.78     0.0
3   2471250.0               0.0       0.00     0.0
4   2471450.0               0.0    -185.10     0.0

In [5]:
df3=df[(df['GL Account'] > 2_480_000) & (df['GL Account'] < 2_490_000)]
df3.loc['Total Income']= df[intCols].sum()
df3

/opt/conda/lib/python3.7/site-packages/pandas/core/indexing.py:723: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)

              GL Account  Allocated Budget     Actual  % Used
47             2480050.0               0.0       0.00    0.00
48             2480250.0               0.0   -1192.90    0.00
49             2480450.0            4840.0     880.87   18.20
50             2480650.0           26200.0    9039.56   34.50
51             2480850.0               0.0   -6275.00    0.00
52             2481050.0               0.0       0.00    0.00
53             2481250.0            5920.0    1022.63   17.27
54             2481450.0           24213.0    4615.93   19.06
55             2481650.0               0.0    -200.00    0.00
56             2481850.0               0.0       0.00    0.00
57             2482050.0            8300.0       0.00    0.00
58             2482250.0            8022.0     405.48    5.05
59             2482450.0            8000.0    1766.14   22.08
60             2482650.0               0.0       0.00    0.00
Total Income         NaN         1555433.0 -870675.35  683.26

In [6]:
'''
#!pip install xlsxwriter
import xlsxwriter

header='FY22 - Q3 Financials as of 5/11/22'
ag='Agency'
bbc='BBC'
adv='Adventure'
startrow=4
startcol=1

writer = pd.ExcelWriter('Campus.xlsx', engine='xlsxwriter')

#AGENCY:
df1.to_excel(writer, sheet_name=ag, startrow=startrow, startcol=startcol)
worksheet1 = writer.sheets[ag]
worksheet1.write(0, 0, header)


#BBC:
df2.to_excel(writer, sheet_name=bbc, startrow=startrow, startcol=startcol)
worksheet2 = writer.sheets[bbc]
worksheet2.write(0, 0, header)


#ADV:
df3.to_excel(writer, sheet_name=adv, startrow=startrow, startcol=startcol)
worksheet3 = writer.sheets[adv]
worksheet3.write(0, 0, header)

writer.save()
print("Done")
'''

'\n#!pip install xlsxwriter\nimport xlsxwriter\n\nheader=\'FY22 - Q3 Financials as of 5/11/22\'\nag=\'Agency\'\nbbc=\'BBC\'\nadv=\'Adventure\'\nstartrow=4\nstartcol=1\n\nwriter = pd.ExcelWriter(\'Campus.xlsx\', engine=\'xlsxwriter\')\n\n#AGENCY:\ndf1.to_excel(writer, sheet_name=ag, startrow=startrow, startcol=startcol)\nworksheet1 = writer.sheets[ag]\nworksheet1.write(0, 0, header)\n\n\n#BBC:\ndf2.to_excel(writer, sheet_name=bbc, startrow=startrow, startcol=startcol)\nworksheet2 = writer.sheets[bbc]\nworksheet2.write(0, 0, header)\n\n\n#ADV:\ndf3.to_excel(writer, sheet_name=adv, startrow=startrow, startcol=startcol)\nworksheet3 = writer.sheets[adv]\nworksheet3.write(0, 0, header)\n\nwriter.save()\nprint("Done")\n'