# QuarterReport

In [1]:
import numpy as np 
import pandas as pd 
import os

file=r'/kaggle/input/datareport/dataReport.csv'
df=pd.read_csv(file)
df.head()

,GL Account,GL Description,Date,Source,Reference Number,Description,Opening Balance,YTD Debits,YTD Credits
0,315,CR,5/10/2022,REGGIE,12345,ReggieRules,NaN,2386,NaN
1,473,CR,3/19/2022,REGGIE,12346,ReggieRules,NaN,2819,NaN
2,266,CR,8/7/2021,REGGIE,12347,ReggieRules,NaN,1041,NaN
3,530,CR,6/21/2022,REGGIE,12348,ReggieRules,NaN,2378,NaN
4,545,CR,7/25/2021,REGGIE,12349,ReggieRules,NaN,1588,NaN

In [2]:
df=df[['GL Account', ' Date', ' YTD Debits', ' YTD Credits']]
df.head()

   GL Account       Date   YTD Debits   YTD Credits
0         315  5/10/2022         2386           NaN
1         473  3/19/2022         2819           NaN
2         266   8/7/2021         1041           NaN
3         530  6/21/2022         2378           NaN
4         545  7/25/2021         1588           NaN

In [3]:
df[[' YTD Debits', ' YTD Credits']]=df[[' YTD Debits', ' YTD Credits']].fillna(0)
df.head()

   GL Account       Date   YTD Debits   YTD Credits
0         315  5/10/2022         2386           0.0
1         473  3/19/2022         2819           0.0
2         266   8/7/2021         1041           0.0
3         530  6/21/2022         2378           0.0
4         545  7/25/2021         1588           0.0

In [4]:
df['DataTotal'] = df.apply((lambda x: x[' YTD Debits'] - x[' YTD Credits']), axis=1)
df.head()

   GL Account       Date   YTD Debits   YTD Credits  DataTotal
0         315  5/10/2022         2386           0.0     2386.0
1         473  3/19/2022         2819           0.0     2819.0
2         266   8/7/2021         1041           0.0     1041.0
3         530  6/21/2022         2378           0.0     2378.0
4         545  7/25/2021         1588           0.0     1588.0

In [5]:
df=df.drop(columns=[' YTD Debits', ' YTD Credits'])
df.head()

   GL Account       Date  DataTotal
0         315  5/10/2022     2386.0
1         473  3/19/2022     2819.0
2         266   8/7/2021     1041.0
3         530  6/21/2022     2378.0
4         545  7/25/2021     1588.0

In [6]:
df=df.groupby(['GL Account', ' Date'])['DataTotal'].sum().reset_index()
df.head()

   GL Account        Date  DataTotal
0         222  10/11/2021      658.0
1         222  11/20/2021     3251.0
2         222  11/22/2021     3260.0
3         222  12/21/2021     1950.0
4         222   2/19/2022     3761.0

In [7]:
df1=df[(df[' Date'] > '7/01/2021') & (df[' Date'] < '9/30/2021')].reset_index()
df1.head(40)

    index  GL Account       Date  DataTotal
0       6         222  8/13/2021      508.0
1      11         223  7/20/2021     3295.0
2      12         223   7/6/2021     1808.0
3      18         224  7/27/2021     3739.0
4      19         224  8/12/2021     3685.0
5      22         225  9/22/2021     3146.0
6      26         226  9/17/2021     3740.0
7      37         227  7/26/2021     2030.0
8      44         228  8/26/2021     2447.0
9      45         228   8/5/2021     1590.0
10     52         229  8/22/2021     3534.0
11     53         229  9/14/2021     3491.0
12     64         231  7/16/2021     1695.0
13     65         231  7/20/2021     2320.0
14     72         232   8/8/2021     2139.0
15     82         234   7/1/2022      903.0
16     83         234   8/5/2021     3931.0
17     96         236   8/3/2021     1072.0
18    100         237  7/14/2021     2502.0
19    101         237  9/20/2021      427.0
20    108         238  7/10/2021     2996.0
21    109         238  7/16/2021     3519.0
22    110         238  7/21/2021     2668.0
23    111         238   9/2/2021     3526.0
24    124         240   7/5/2021     2115.0
25    125         240  9/24/2021     2126.0
26    134         242  7/12/2021     1887.0
27    135         242  8/20/2021     1511.0
28    136         242  8/23/2021      313.0
29    143         243  8/13/2021     3039.0
30    150         244  7/28/2021      440.0
31    151         244  9/27/2021     1631.0
32    157         245  9/22/2021     3098.0
33    158         245  9/24/2021     1596.0
34    166         246  8/13/2021     1705.0
35    167         246  8/14/2021     3477.0
36    168         246  9/23/2021      641.0
37    172         247  9/19/2021     3274.0
38    186         249   7/1/2022     1253.0
39    187         249   8/5/2021     1692.0

In [8]:
df1=df1.groupby(['GL Account'])['DataTotal'].sum().reset_index()
df1.head(1000)

     GL Account  DataTotal
0           222      508.0
1           223     5103.0
2           224     7424.0
3           225     3146.0
4           226     3740.0
..          ...        ...
273         551     3345.0
274         552     7771.0
275         553    11709.0
276         554      588.0
277         555     5423.0

[278 rows x 2 columns]